spring:
  datasource:
    url: jdbc:mysql://10.208.63.130:30201/source?encoding=UTF-8
    username: root
    password: changeme
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create